name: Backend Deployment

on:
  # workflow_dispatch
  push:
    branches: [Backend-master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'Backend-master'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run automated tests
        run: dotnet test -c Release --no-build

      - name: Publish
        run: dotnet publish -r linux-x64 -o cosmos-webapp-be/

      - name: Copy to deployment server via scp
        uses: garygrossgarten/github-action-scp@v0.5.3
        with:
          local: /home/runner/work/Cosmos/Cosmos/cosmos-webapp-be
          remote: ${{ secrets.REMOTE_BE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          concurrency: 500

      - name: Restart cosmos-webapp-be service via ssh
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: |
            systemctl restart cosmos-webapp-be
            nginx -s reload

          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
