# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend Deployment

on:
  workflow_dispatch
  # push:
  #   branches: [Frontend-master]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: 'Frontend-master'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build for production
        run: CI=false npm run build --if-present

      - name: Copy to deployment server via scp
        uses: garygrossgarten/github-action-scp@v0.5.3
        with:
          local: ./build/
          remote: ${{ secrets.REMOTE_FE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          concurrency: 500

      - name: Restart nginx
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: |
            nginx -s reload

          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
