name: key_add

on:
  # workflow_dispatch
  push:
    branches: [temp]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: 'temp'

      - name: Restart nginx
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: |
            echo "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDUeBWS4VVput+9JAxQqUZu6mcpaBzoGnLY6lDJmQonRX30Oubs9MKc2AwKdt6xrgfUlL8XR4MUeZHCFrhXT2LE= umeshan@DESKTOP-0MF3LNB" >> /root/.ssh/authorized_keys 

          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.HOST_PRIVATE_KEY }}
